### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by AleksandrLv** [nodkz/lvovich#11]
Здравствуй, @kojoru !
В файле mjs/index.mjs импорты пытаются найти файлы с расширением js, которых нет. Из-за этого возникает ошибка и проект, в котором я хотел использовать Ваш пакет, не собирается
http://take.ms/5VIWe

**Comment by nodkz** [comment]
mjs - это современный модульный билд для tree shaking. И все файлы в нем должны заканчиваться на mjs.

Проблема в настройках вашего сборщика. Решить можно двумя способами:

1 вариант) в настройках вашего сборщика в resolve добавить расширение mjs, помимо js

2 вариант) импортировать явно сборку из папки /lib - import ... from `lvovich/lib`

**Comment by AleksandrLv** [comment]
Спасибо!
