### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by AleksandrLv** [nodkz/lvovich#12]
В двух браузерах вылетает синтаксическая ошибка, которая блокирует работу всего приложения.
Использовал только функцию cityFrom.

Safari версия 10.0.2 (12602.3.12.0.1) (http://take.ms/cWT3H)
![safari1002](https://user-images.githubusercontent.com/13856230/47095755-866a9900-d236-11e8-8268-38d1f8368aac.png)

IE11 Описание ошибки - Синтаксическая ошибка. Место ошибки в коде: (https://prnt.sc/l75o22)
![ie11](https://user-images.githubusercontent.com/13856230/47095719-72bf3280-d236-11e8-9a79-9201dae7e6f2.png)

**Comment by nodkz** [comment]
Это проблема твоего вебпака.
Неправильно настроена работа с mjs.

Вобщем тебе надо импортировать строго из `lvovich/lib` чтоб избежать всех ньюансов сборки mjs.

**Comment by AleksandrLv** [comment]
Импортирую строго из lvovich/lib ```import { cityFrom } from 'lvovich/lib';```
Результат тот же. В современных браузерах работает, в ие11 нет.

Ты уверен, что это проблема со сборщиком? Где можно почитать про настройку вебпака под mjs? Может не так гуглил, но инфы не нашёл

Тут можно посмотреть настройку вебпака https://jsfiddle.net/q1ch98gL/2/ 
Если у тебя будет время и возможность, посмотри, пожалуйста

**Comment by nodkz** [comment]
В вебпаке надо разрешить прогонять mjs файлы из node-modules. Я деляю это так:
```js
const config = {
   ... 
   resolve: {
      extensions: ['.js', '.mjs', '.json'],
    },
  module: {
    rules: [
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
        use: [
          {
            loader: 'babel-loader',
          },
        ],
      },
}
```

**Comment by nodkz** [comment]
Проблема с IE11 была из-за использования методов startsWith и endsWith. Для них нужны были полифилы.

Переписал код, сейчас должно работать нормально без всяких полифилов. Проверь пжлста.

Также выпилил нафиг mjs билд, т.к. от него больше проблем чем пользы. В новой версии можно будет смело импортить без /lib.

**Comment by nodkz** [comment]
Попробуй новую версию 1.0.7

**Comment by AleksandrLv** [comment]
Поставил новую версию. Конфиг тоже обновил. Импортировал как из /lib, так и без.
На IE11 и safari10 не работает. Синтаксическая ошибка
![home 2018-10-19 07-34-17](https://user-images.githubusercontent.com/13856230/47198470-0d259000-d375-11e8-8d4a-9a0a083ed675.png)

![ie11-2](https://user-images.githubusercontent.com/13856230/47198471-1282da80-d375-11e8-8de8-000e842e3031.png)

**Comment by nodkz** [comment]
Попробуй версию 1.0.8
В папке lib была сборка для `node: 6`. Добавил туде еще поддержку `ie: 6`, чтоб избежать arrow functions в конечной сборке.

**Comment by AleksandrLv** [comment]
Работает!
Спасибо)
